compatibility_date = "2023-10-16"
main = "src/index.ts"
name = "r2-webdav"

compatibility_flags = ["nodejs_compat"]

# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
head_sampling_rate = 1
